// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table internal header
//
// Internal details; most calling programs do not need this header,
// unless using verilator public meta comments.

#ifndef VERILATED_VTB_TCP_HANDSHAKE__SYMS_H_
#define VERILATED_VTB_TCP_HANDSHAKE__SYMS_H_  // guard

#include "verilated.h"

// INCLUDE MODEL CLASS

#include "Vtb_tcp_handshake.h"

// INCLUDE MODULE CLASSES
#include "Vtb_tcp_handshake___024root.h"
#include "Vtb_tcp_handshake_xpm_memory_tdpram__pi7.h"

// DPI TYPES for DPI Export callbacks (Internal use)

// SYMS CLASS (contains all model state)
class alignas(VL_CACHE_LINE_BYTES)Vtb_tcp_handshake__Syms final : public VerilatedSyms {
  public:
    // INTERNAL STATE
    Vtb_tcp_handshake* const __Vm_modelp;
    bool __Vm_activity = false;  ///< Used by trace routines to determine change occurred
    uint32_t __Vm_baseCode = 0;  ///< Used by trace routines when tracing multiple models
    VlDeleter __Vm_deleter;
    bool __Vm_didInit = false;

    // MODULE INSTANCE STATE
    Vtb_tcp_handshake___024root    TOP;
    Vtb_tcp_handshake_xpm_memory_tdpram__pi7 TOP__tb_tcp_handshake__DOT__u_dut__DOT__u_riscv__DOT__riscv_cpu_generation__DOT__u_riscv_cpu__DOT__u_instru_ram__DOT__gen_xilinx_xpm_tdpram__DOT__xpm_bank__BRA__0__KET____DOT__u_xpm_memory_tdpram_bank;
    Vtb_tcp_handshake_xpm_memory_tdpram__pi7 TOP__tb_tcp_handshake__DOT__u_dut__DOT__u_riscv__DOT__riscv_cpu_generation__DOT__u_riscv_cpu__DOT__u_instru_ram__DOT__gen_xilinx_xpm_tdpram__DOT__xpm_bank__BRA__10__KET____DOT__u_xpm_memory_tdpram_bank;
    Vtb_tcp_handshake_xpm_memory_tdpram__pi7 TOP__tb_tcp_handshake__DOT__u_dut__DOT__u_riscv__DOT__riscv_cpu_generation__DOT__u_riscv_cpu__DOT__u_instru_ram__DOT__gen_xilinx_xpm_tdpram__DOT__xpm_bank__BRA__11__KET____DOT__u_xpm_memory_tdpram_bank;
    Vtb_tcp_handshake_xpm_memory_tdpram__pi7 TOP__tb_tcp_handshake__DOT__u_dut__DOT__u_riscv__DOT__riscv_cpu_generation__DOT__u_riscv_cpu__DOT__u_instru_ram__DOT__gen_xilinx_xpm_tdpram__DOT__xpm_bank__BRA__12__KET____DOT__u_xpm_memory_tdpram_bank;
    Vtb_tcp_handshake_xpm_memory_tdpram__pi7 TOP__tb_tcp_handshake__DOT__u_dut__DOT__u_riscv__DOT__riscv_cpu_generation__DOT__u_riscv_cpu__DOT__u_instru_ram__DOT__gen_xilinx_xpm_tdpram__DOT__xpm_bank__BRA__13__KET____DOT__u_xpm_memory_tdpram_bank;
    Vtb_tcp_handshake_xpm_memory_tdpram__pi7 TOP__tb_tcp_handshake__DOT__u_dut__DOT__u_riscv__DOT__riscv_cpu_generation__DOT__u_riscv_cpu__DOT__u_instru_ram__DOT__gen_xilinx_xpm_tdpram__DOT__xpm_bank__BRA__14__KET____DOT__u_xpm_memory_tdpram_bank;
    Vtb_tcp_handshake_xpm_memory_tdpram__pi7 TOP__tb_tcp_handshake__DOT__u_dut__DOT__u_riscv__DOT__riscv_cpu_generation__DOT__u_riscv_cpu__DOT__u_instru_ram__DOT__gen_xilinx_xpm_tdpram__DOT__xpm_bank__BRA__15__KET____DOT__u_xpm_memory_tdpram_bank;
    Vtb_tcp_handshake_xpm_memory_tdpram__pi7 TOP__tb_tcp_handshake__DOT__u_dut__DOT__u_riscv__DOT__riscv_cpu_generation__DOT__u_riscv_cpu__DOT__u_instru_ram__DOT__gen_xilinx_xpm_tdpram__DOT__xpm_bank__BRA__1__KET____DOT__u_xpm_memory_tdpram_bank;
    Vtb_tcp_handshake_xpm_memory_tdpram__pi7 TOP__tb_tcp_handshake__DOT__u_dut__DOT__u_riscv__DOT__riscv_cpu_generation__DOT__u_riscv_cpu__DOT__u_instru_ram__DOT__gen_xilinx_xpm_tdpram__DOT__xpm_bank__BRA__2__KET____DOT__u_xpm_memory_tdpram_bank;
    Vtb_tcp_handshake_xpm_memory_tdpram__pi7 TOP__tb_tcp_handshake__DOT__u_dut__DOT__u_riscv__DOT__riscv_cpu_generation__DOT__u_riscv_cpu__DOT__u_instru_ram__DOT__gen_xilinx_xpm_tdpram__DOT__xpm_bank__BRA__3__KET____DOT__u_xpm_memory_tdpram_bank;
    Vtb_tcp_handshake_xpm_memory_tdpram__pi7 TOP__tb_tcp_handshake__DOT__u_dut__DOT__u_riscv__DOT__riscv_cpu_generation__DOT__u_riscv_cpu__DOT__u_instru_ram__DOT__gen_xilinx_xpm_tdpram__DOT__xpm_bank__BRA__4__KET____DOT__u_xpm_memory_tdpram_bank;
    Vtb_tcp_handshake_xpm_memory_tdpram__pi7 TOP__tb_tcp_handshake__DOT__u_dut__DOT__u_riscv__DOT__riscv_cpu_generation__DOT__u_riscv_cpu__DOT__u_instru_ram__DOT__gen_xilinx_xpm_tdpram__DOT__xpm_bank__BRA__5__KET____DOT__u_xpm_memory_tdpram_bank;
    Vtb_tcp_handshake_xpm_memory_tdpram__pi7 TOP__tb_tcp_handshake__DOT__u_dut__DOT__u_riscv__DOT__riscv_cpu_generation__DOT__u_riscv_cpu__DOT__u_instru_ram__DOT__gen_xilinx_xpm_tdpram__DOT__xpm_bank__BRA__6__KET____DOT__u_xpm_memory_tdpram_bank;
    Vtb_tcp_handshake_xpm_memory_tdpram__pi7 TOP__tb_tcp_handshake__DOT__u_dut__DOT__u_riscv__DOT__riscv_cpu_generation__DOT__u_riscv_cpu__DOT__u_instru_ram__DOT__gen_xilinx_xpm_tdpram__DOT__xpm_bank__BRA__7__KET____DOT__u_xpm_memory_tdpram_bank;
    Vtb_tcp_handshake_xpm_memory_tdpram__pi7 TOP__tb_tcp_handshake__DOT__u_dut__DOT__u_riscv__DOT__riscv_cpu_generation__DOT__u_riscv_cpu__DOT__u_instru_ram__DOT__gen_xilinx_xpm_tdpram__DOT__xpm_bank__BRA__8__KET____DOT__u_xpm_memory_tdpram_bank;
    Vtb_tcp_handshake_xpm_memory_tdpram__pi7 TOP__tb_tcp_handshake__DOT__u_dut__DOT__u_riscv__DOT__riscv_cpu_generation__DOT__u_riscv_cpu__DOT__u_instru_ram__DOT__gen_xilinx_xpm_tdpram__DOT__xpm_bank__BRA__9__KET____DOT__u_xpm_memory_tdpram_bank;

    // SCOPE NAMES
    VerilatedScope __Vscope_TOP;
    VerilatedScope __Vscope_tb_tcp_handshake;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_bridge;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_bridge__u_rx;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_bridge__u_rx__gen_rxd_iddr__BRA__0__KET____u_rxd_iddr;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_bridge__u_rx__gen_rxd_iddr__BRA__1__KET____u_rxd_iddr;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_bridge__u_rx__gen_rxd_iddr__BRA__2__KET____u_rxd_iddr;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_bridge__u_rx__gen_rxd_iddr__BRA__3__KET____u_rxd_iddr;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_bridge__u_rx__gen_rxd_idelay__BRA__0__KET____u_rxd_idelay;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_bridge__u_rx__gen_rxd_idelay__BRA__1__KET____u_rxd_idelay;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_bridge__u_rx__gen_rxd_idelay__BRA__2__KET____u_rxd_idelay;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_bridge__u_rx__gen_rxd_idelay__BRA__3__KET____u_rxd_idelay;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_bridge__u_rx__u_idelayctrl;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_bridge__u_rx__u_rx_ctl_iddr;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_bridge__u_rx__u_rx_ctl_idelay;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_bridge__u_rx__u_rxc_bufg;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_bridge__u_tx;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_bridge__u_tx__gen_txd_oddr__BRA__0__KET____u_txd_oddr;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_bridge__u_tx__gen_txd_oddr__BRA__1__KET____u_txd_oddr;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_bridge__u_tx__gen_txd_oddr__BRA__2__KET____u_txd_oddr;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_bridge__u_tx__gen_txd_oddr__BRA__3__KET____u_txd_oddr;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_bridge__u_tx__u_tx_ctl_oddr;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_bridge__u_tx__u_txc_oddr;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_build_time;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_cpu_channel;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_cpu_channel__u_package_fifo_cpu_rd;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_cpu_channel__u_package_fifo_cpu_rd__none_blk_mode;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_cpu_channel__u_package_fifo_cpu_rd__none_blk_mode__data_ram_dual__u_data_ram;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_cpu_channel__u_package_fifo_cpu_rd__none_blk_mode__data_ram_dual__u_data_ram__gen_inferred_ram;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_cpu_channel__u_package_fifo_cpu_rd__none_blk_mode__nb_dual_clk_cdc__u_para_fifo;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_cpu_channel__u_package_fifo_cpu_rd__none_blk_mode__nb_dual_clk_cdc__u_rptr_sync;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_cpu_channel__u_package_fifo_cpu_rd__none_blk_mode__nb_rptr_cdc;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_cpu_channel__u_package_fifo_cpu_rd__none_blk_mode__nb_rptr_cdc__u_para_fifo_wclk;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_cpu_channel__u_package_fifo_cpu_wr;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_cpu_channel__u_package_fifo_cpu_wr__none_blk_mode;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_cpu_channel__u_package_fifo_cpu_wr__none_blk_mode__data_ram_dual__u_data_ram;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_cpu_channel__u_package_fifo_cpu_wr__none_blk_mode__data_ram_dual__u_data_ram__gen_inferred_ram;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_cpu_channel__u_package_fifo_cpu_wr__none_blk_mode__nb_dual_clk_cdc__u_para_fifo;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_cpu_channel__u_package_fifo_cpu_wr__none_blk_mode__nb_dual_clk_cdc__u_rptr_sync;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_cpu_channel__u_package_fifo_cpu_wr__none_blk_mode__nb_rptr_cdc;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_cpu_channel__u_package_fifo_cpu_wr__none_blk_mode__nb_rptr_cdc__u_para_fifo_wclk;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_cpu_channel__u_pktfifo2ram_int;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_cpu_channel__u_ram2pktfifo_int;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_cpu_channel__u_sop_eop_gen;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_gmii2mac;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_gmii2mac__u_eth_presemble;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_gmii2mac__u_eth_presemble__u_fix_delay;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_gmii2mac__u_eth_presemble__u_fix_delay__delay_using_ram_generation__u_dly_data_buf;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_gmii2mac__u_eth_presemble__u_fix_delay__delay_using_ram_generation__u_dly_data_buf__gen_inferred_ram;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_gmii2mac__u_mac_top;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_gmii2mac__u_mac_top__u_mac_rx;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_gmii2mac__u_mac_top__u_mac_rx__crc_chk_gen__u_crc;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_gmii2mac__u_mac_top__u_mac_rx__crc_chk_gen__u_crc__crc32_d8_gen;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_gmii2mac__u_mac_top__u_mac_rx__u_sop_eop_gen;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_gmii2mac__u_mac_top__u_mac_tx;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_gmii2mac__u_mac_top__u_mac_tx__u_crc;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_gmii2mac__u_mac_top__u_mac_tx__u_crc__crc32_d8_gen;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_gmii2mac__u_mac_top__u_mac_tx__u_fix_delay;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_gmii2mac__u_mac_top__u_mac_tx__u_fix_delay__delay_using_ram_generation__u_dly_data_buf;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_gmii2mac__u_mac_top__u_mac_tx__u_fix_delay__delay_using_ram_generation__u_dly_data_buf__gen_inferred_ram;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_gmii2mac__u_rx_asyncfifo;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_pll;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_pll__u_bufg_125;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_pll__u_bufg_125_tx;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_pll__u_bufg_200;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_pll__u_bufg_50_cpu;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_pll__u_mmcm;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_reg;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_reg__RAMIF_program_ram;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__lcpu_sim__u_lcpu_bfm;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_RiscV32_LocalBus;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_RiscV32_LocalBus__u_RiscV32IntfBridge;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_RiscV32_LocalBus__u_picorv32;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_instru_ram;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_instru_ram__gen_xilinx_xpm_tdpram;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_instru_ram__gen_xilinx_xpm_tdpram__xpm_bank__BRA__0__KET__;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_instru_ram__gen_xilinx_xpm_tdpram__xpm_bank__BRA__0__KET____u_xpm_memory_tdpram_bank;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_instru_ram__gen_xilinx_xpm_tdpram__xpm_bank__BRA__10__KET__;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_instru_ram__gen_xilinx_xpm_tdpram__xpm_bank__BRA__10__KET____u_xpm_memory_tdpram_bank;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_instru_ram__gen_xilinx_xpm_tdpram__xpm_bank__BRA__11__KET__;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_instru_ram__gen_xilinx_xpm_tdpram__xpm_bank__BRA__11__KET____u_xpm_memory_tdpram_bank;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_instru_ram__gen_xilinx_xpm_tdpram__xpm_bank__BRA__12__KET__;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_instru_ram__gen_xilinx_xpm_tdpram__xpm_bank__BRA__12__KET____u_xpm_memory_tdpram_bank;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_instru_ram__gen_xilinx_xpm_tdpram__xpm_bank__BRA__13__KET__;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_instru_ram__gen_xilinx_xpm_tdpram__xpm_bank__BRA__13__KET____u_xpm_memory_tdpram_bank;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_instru_ram__gen_xilinx_xpm_tdpram__xpm_bank__BRA__14__KET__;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_instru_ram__gen_xilinx_xpm_tdpram__xpm_bank__BRA__14__KET____u_xpm_memory_tdpram_bank;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_instru_ram__gen_xilinx_xpm_tdpram__xpm_bank__BRA__15__KET__;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_instru_ram__gen_xilinx_xpm_tdpram__xpm_bank__BRA__15__KET____u_xpm_memory_tdpram_bank;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_instru_ram__gen_xilinx_xpm_tdpram__xpm_bank__BRA__1__KET__;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_instru_ram__gen_xilinx_xpm_tdpram__xpm_bank__BRA__1__KET____u_xpm_memory_tdpram_bank;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_instru_ram__gen_xilinx_xpm_tdpram__xpm_bank__BRA__2__KET__;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_instru_ram__gen_xilinx_xpm_tdpram__xpm_bank__BRA__2__KET____u_xpm_memory_tdpram_bank;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_instru_ram__gen_xilinx_xpm_tdpram__xpm_bank__BRA__3__KET__;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_instru_ram__gen_xilinx_xpm_tdpram__xpm_bank__BRA__3__KET____u_xpm_memory_tdpram_bank;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_instru_ram__gen_xilinx_xpm_tdpram__xpm_bank__BRA__4__KET__;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_instru_ram__gen_xilinx_xpm_tdpram__xpm_bank__BRA__4__KET____u_xpm_memory_tdpram_bank;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_instru_ram__gen_xilinx_xpm_tdpram__xpm_bank__BRA__5__KET__;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_instru_ram__gen_xilinx_xpm_tdpram__xpm_bank__BRA__5__KET____u_xpm_memory_tdpram_bank;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_instru_ram__gen_xilinx_xpm_tdpram__xpm_bank__BRA__6__KET__;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_instru_ram__gen_xilinx_xpm_tdpram__xpm_bank__BRA__6__KET____u_xpm_memory_tdpram_bank;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_instru_ram__gen_xilinx_xpm_tdpram__xpm_bank__BRA__7__KET__;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_instru_ram__gen_xilinx_xpm_tdpram__xpm_bank__BRA__7__KET____u_xpm_memory_tdpram_bank;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_instru_ram__gen_xilinx_xpm_tdpram__xpm_bank__BRA__8__KET__;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_instru_ram__gen_xilinx_xpm_tdpram__xpm_bank__BRA__8__KET____u_xpm_memory_tdpram_bank;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_instru_ram__gen_xilinx_xpm_tdpram__xpm_bank__BRA__9__KET__;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_instru_ram__gen_xilinx_xpm_tdpram__xpm_bank__BRA__9__KET____u_xpm_memory_tdpram_bank;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_riscv_reg;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__riscv_cpu_generation__u_riscv_cpu__u_riscv_reg__RAMIF_instuct_ram;
    VerilatedScope __Vscope_tb_tcp_handshake__u_dut__u_riscv__u_lcpu_merge;

    // CONSTRUCTORS
    Vtb_tcp_handshake__Syms(VerilatedContext* contextp, const char* namep, Vtb_tcp_handshake* modelp);
    ~Vtb_tcp_handshake__Syms();

    // METHODS
    const char* name() { return TOP.name(); }
};

#endif  // guard
