#!/usr/bin/env python3
"""bin_to_jtag_tcl.py — 把 firmware.bin 转成 JTAG-AXI 逐字写事务 Tcl。

与 updatemem 完全等价: 第 i 个字 = bin 的第 [4i:4i+4] 字节按 RISC-V 小端解出,
写到指令 RAM 字地址 0x10000 + i (AXI 地址 = LCPU 字地址, 不乘 4)。

Usage: python3 bin_to_jtag_tcl.py <firmware.bin> <output_axi_body.tcl>
产出:
  1. <output_axi_body.tcl>        — 逐字写事务, 由 jtag_load_fw.tcl source
  2. <同目录>/fw_expected_words.txt — 每个字的期望值(大写 hex), 由 verify_fw.tcl 读
"""

import sys
import struct
import pathlib

BASE_ADDR = 0x10000  # 指令 RAM 字基址


def bin_to_tcl(bin_file: pathlib.Path, tcl_file: pathlib.Path) -> None:
    data = bin_file.read_bytes()

    # 补足到 4 字节整数倍
    rem = len(data) % 4
    if rem:
        data += b'\x00' * (4 - rem)

    n_words = len(data) // 4

    # 找最后一个非零字, 跳过尾部全零 padding (不跳过开头: PC=0 对应 bin[0])
    last_nonzero = -1
    for i in range(n_words - 1, -1, -1):
        if any(b != 0 for b in data[i*4:i*4+4]):
            last_nonzero = i
            break
    if last_nonzero < 0:
        print("Warning: firmware binary is all zeros.")
        last_nonzero = 0

    words = [struct.unpack('<I', data[i*4:i*4+4])[0] for i in range(last_nonzero + 1)]

    # 1) 写事务 Tcl (引用 jtag_load_fw.tcl 里定义的 $hw_axi 变量)
    with tcl_file.open('w', encoding='ascii') as f:
        f.write("# Auto-generated by bin_to_jtag_tcl.py -- do not edit\n")
        f.write("# Write instruction RAM word by word, addr 0x10000+i (word addr, little-endian)\n")
        for i, w in enumerate(words):
            f.write(f"create_hw_axi_txn w{i} $hw_axi -type write "
                    f"-address 0x{BASE_ADDR + i:08X} -data 0x{w:08X} -len 1\n")
            f.write(f"run_hw_axi w{i}\n")

    # 2) 期望值列表 (供 verify_fw.tcl 回读比对)
    expect_file = tcl_file.with_name('fw_expected_words.txt')
    with expect_file.open('w', encoding='ascii') as f:
        for w in words:
            f.write(f"{w:08X}\n")

    print(f"  TCL generated: {len(words)} words, "
          f"addr 0x{BASE_ADDR:08X}..0x{BASE_ADDR + last_nonzero:08X}")
    print(f"  expect words:  {expect_file}")


if __name__ == '__main__':
    if len(sys.argv) != 3:
        print("Usage: python3 bin_to_jtag_tcl.py <firmware.bin> <output_axi_body.tcl>")
        sys.exit(1)

    input_bin = pathlib.Path(sys.argv[1])
    output_tcl = pathlib.Path(sys.argv[2])

    if not input_bin.exists():
        print(f"Error: input file not found: {input_bin}")
        sys.exit(1)

    bin_to_tcl(input_bin, output_tcl)
