set script_dir [file dirname [file normalize [info script]]]
set proj_name "RiscV_WebSoC"
set proj_dir  $script_dir
set rtl_dir   [file normalize [file join $script_dir ../rtl]]
set ila_home  /home/haitaoz/work/FPGA_Prj/fpga_ila-snapshot-20260812133532
set ila_rtl   [file join $ila_home rtl]

create_project -force $proj_name $proj_dir -part xc7a35tfgg484-2
puts "\[OK\] Project created"

# 自动生成版本时间戳 (FPGA 无 RTC, 编译期烤入当天日期, 供 read_back.tcl 验明正身)
set now [clock seconds]
set bd  [clock format $now -format "%Y%m%d"]
set bt  [clock format $now -format "%H%M%S"]
set f   [open [file join $rtl_dir fpga_build_time.v] w]
puts $f "// Auto-generated by build.tcl -- version stamp"
puts $f "module fpga_build_time ("
puts $f "    output wire \[31:0\] build_date,"
puts $f "    output wire \[31:0\] build_time"
puts $f ");"
puts $f "    assign build_date = 32'h$bd;"
puts $f "    assign build_time = 32'h$bt;"
puts $f "endmodule"
close $f
puts "\[OK\] fpga_build_time.v = 0x$bd / 0x$bt"

foreach f [lsort [glob -nocomplain ${rtl_dir}/*.v ${rtl_dir}/*.sv]] {
    add_files -norecurse $f
}
puts "\[OK\] Added [llength [glob -nocomplain ${rtl_dir}/*.v ${rtl_dir}/*.sv]] RTL files"

# ILA RTL files (参考 RiscV_WebSoC_3 方式: glob 所有 .v + .vh)
foreach f [lsort [glob -nocomplain ${ila_rtl}/*.v]] { add_files -norecurse $f }
foreach f [lsort [glob -nocomplain ${ila_rtl}/*.vh]] { add_files -norecurse $f }
set_property INCLUDE_DIRS [list ${rtl_dir} ${ila_rtl}] [current_fileset]
puts "\[OK\] Added ILA RTL files"

set_property FILE_TYPE SYSTEMVERILOG [get_files -filter {FILE_TYPE == Verilog}]
set_property top webserver_cpu_top [current_fileset]
update_compile_order -fileset sources_1

add_files -fileset constrs_1 -norecurse [file join $script_dir pins.xdc]
add_files -fileset constrs_1 -norecurse [file join $script_dir timing.xdc]

# JTAG→AXI 桥 IP (rtl/jtag_cpu_xilinx.v 例化了 jtag_axi_0, 不 read_ip 会报 unknown module)
read_ip [file join $script_dir jtag_axi_0.xci]
puts "\[OK\] read_ip jtag_axi_0"

puts "Running Synthesis..."
launch_runs synth_1 -jobs 8
wait_on_run synth_1

puts "Running Implementation..."
launch_runs impl_1 -to_step write_bitstream -jobs 8
wait_on_run impl_1

set bit_src "$proj_dir/${proj_name}.runs/impl_1/webserver_cpu_top.bit"
set bit_dst "$proj_dir/${proj_name}.bit"
if {[file exists $bit_src]} { file copy -force $bit_src $bit_dst; puts "Bitstream: $bit_dst" }

open_run impl_1
report_timing_summary -file "$proj_dir/timing_summary.rpt"
report_utilization    -file "$proj_dir/utilization.rpt"
# 生成 BRAM 内存映射文件 (updatemem 合并固件用, 必须每次 build 重新生成)
write_mem_info -force "$proj_dir/${proj_name}.mmi"
close_design
puts "BUILD COMPLETE"
